const { test, expect } = require('../fixtures/test.fixture');
const { ensureLocation, ensureLoggedIn, gotoAuthed, gotoWithRetry, waitForAppBoot, API } = require('../utils/app');
const { addFirstProductToCart, ensureDeliveryAddress, chooseCashPayment, handleScheduleDialogIfShown, placeOrderButton, gotoCheckout } = require('../flows/order.flow');
const { readStore } = require('../utils/store');
const { orderIdFrom, assertIdentity, cartLines, validateBill } = require('../utils/policy');
const { assertManagedRun, readManifest, updateManifest, recordOrder } = require('../utils/manifest');
const { testUser } = require('../utils/env');
test('places a COD order end-to-end and sees it in order history @smoke @checkout', async ({ page }, testInfo) => {
  test.setTimeout(300_000);
  assertManagedRun();
  if (readManifest().submissionAttempted || readManifest().orders.length) throw new Error('Order attempt cannot be replayed; reconcile the recorded attempt');
  await ensureLocation(page);
  await ensureLoggedIn(page);
  await gotoWithRetry(page, '/en/home');
  await waitForAppBoot(page);
  await page.locator('.merchant-card:visible').first().click();
  await page.waitForURL(/\/m(\/|$)/);
  const added = await addFirstProductToCart(page);
  await gotoCheckout(page, added.cart_id);
  await ensureDeliveryAddress(page);
  const payment = await chooseCashPayment(page);
  const state = await readStore(page);
  assertIdentity(state.user, testUser.email, readManifest().userId);
  const lines = cartLines(state.items);
  const bill = validateBill(state.cart);
  let submitted = 0;
  await page.route((url) => url.pathname === API.placeOrder, async (route) => {
    if (route.request().method() !== 'POST') return route.continue();
    const payload = route.request().postDataJSON();
    if (submitted || String(payload.user_id) !== String(state.user.id) || String(payload.cart_id) !== String(state.cart.cart_id) || String(payload.payment_mode_id) !== String(payment.payment_mode_id)) return route.abort('blockedbyclient');
    submitted++;
    updateManifest({ submissionAttempted: { cartId: payload.cart_id, paymentModeId: payload.payment_mode_id, userId: payload.user_id, at: new Date().toISOString() } });
    return route.continue();
  });
  const origin = new URL(process.env.BASE_URL).origin;
  await page.context().route('**/*', async (route) => {
    if (route.request().isNavigationRequest() && new URL(route.request().url()).origin !== origin) return route.abort('blockedbyclient');
    return route.fallback();
  });
  const waiting = page.waitForResponse((r) => new URL(r.url()).pathname === API.placeOrder && r.request().method() === 'POST', { timeout: 90_000 });
  waiting.catch(() => {});
  const place = placeOrderButton(page);
  await expect(place).toBeEnabled();
  await place.click();
  if (await handleScheduleDialogIfShown(page)) { await expect(place).toBeEnabled(); await place.click(); }
  const response = await waiting;
  expect(response.ok(), 'order HTTP response').toBeTruthy();
  const body = await response.json();
  const orderId = orderIdFrom(body);
  recordOrder({ orderId, cartId: state.cart.cart_id, userId: state.user.id, paymentModeId: payment.payment_mode_id, expectedBill: bill, expectedLines: lines, reconciliation: 'test-tenant-order-retained' });
  await testInfo.attach('created-order', { body: Buffer.from(JSON.stringify({ orderId, bill, lines })), contentType: 'application/json' });
  expect(submitted, 'exactly one order submission').toBe(1);
  if (body.data?.total_amount != null) expect(Number(body.data.total_amount)).toBeCloseTo(bill.total, 2);
  await page.waitForURL(/order\/success|profile\/order/, { timeout: 45_000 });
  await gotoAuthed(page, '/en/profile/orders');
  const card = page.locator(`#orders [data-test-id="test-id-${orderId}"]`);
  await expect(card).toBeVisible();
  await expect(card).toContainText(String(orderId));
});
